### ISSUE TITLE
Alter the timeout setting?

### ISSUE THREAD

**Issue by curtismchale** [strangerstudios/wp-bouncer#6]
Are we taking a PR for being able to alter the timeout setting? We could add another parameter to the localize script and set the default to `5000` but pair it with a filter that allows someone to change it to...whatever.

**Comment by ideadude** [comment]
That would be great.

Can add it as a localized variable called timeout or something similar here:
https://github.com/strangerstudios/wp-bouncer/blob/dev/wp-bouncer.php#L70

A filter named "wp_bouncer_ajax_timeout" or something similar is good.

Then have the JS use the value from the var.

Thanks!
